### ISSUE TITLE
Update to version 14.7

### ISSUE THREAD

**Issue by duboism** [Rfam/rfam-taxonomy#1]
Hello,

[Rfam 14.7 has been released](https://xfam.wordpress.com/2021/12/21/rfam-release-14-7/) in December 2021. Could you update the data ?

**Comment by AntonPetrov** [comment]
@duboism Thank you for pointing this out! I will update the repo and add it to the Rfam release process to make sure it gets updated regularly. Stay tuned

**Comment by duboism** [comment]
Thanks in advance.
